//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupOnTheGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFoulsAndMisconduct
    {
        public long Id { get; set; }
        public string card_color { get; set; }
        public System.DateTime action_taken_datetime { get; set; }
        public long player_id { get; set; }
        public long match_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<long> updated_by { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblMatch tblMatch { get; set; }
        public virtual tblPlayer tblPlayer { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
