//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupOnTheGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatch
    {
        public long Id { get; set; }
        public long team_a_id { get; set; }
        public int team_a_score { get; set; }
        public long team_b_id { get; set; }
        public Nullable<int> team_b_score { get; set; }
        public Nullable<System.DateTime> match_datetime { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<long> updated_by { get; set; }
    }
}
