//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupOnTheGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPlayer()
        {
            this.tblFoulsAndMisconducts = new HashSet<tblFoulsAndMisconduct>();
        }
    
        public long Id { get; set; }
        public long name { get; set; }
        public int jercy_no { get; set; }
        public long team_id { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<long> updated_by { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFoulsAndMisconduct> tblFoulsAndMisconducts { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblTeam tblTeam { get; set; }
        public virtual tblUser tblUser1 { get; set; }
    }
}
