//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupOnTheGo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeam
    {
        public long Id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<long> created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<long> updated_by { get; set; }
    }
}
