//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WorldCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loginID()
        {
            this.countries = new HashSet<country>();
            this.teamPlayers = new HashSet<teamPlayer>();
            this.newsArticles = new HashSet<newsArticle>();
            this.teamGroups = new HashSet<teamGroup>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string user_Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<country> countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teamPlayer> teamPlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newsArticle> newsArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teamGroup> teamGroups { get; set; }
    }
}
