//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WorldCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsArticle
    {
        public int Id { get; set; }
        public string news { get; set; }
        public string article { get; set; }
    
        public virtual loginID loginID { get; set; }
    }
}
