//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_WorldCup
{
    using System;
    using System.Collections.Generic;
    
    public partial class teamPlayer
    {
        public int playerID { get; set; }
        public string fullName { get; set; }
        public string teamCountry { get; set; }
        public int jerseyNum { get; set; }
        public string position { get; set; }
        public string Club { get; set; }
        public string photo { get; set; }
    }
}
