INSERT INTO country (name, code, fifaQualified) VALUES ('Afghanistan', 'AF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Albania', 'AL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Algeria', 'DZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('American Samoa', 'AS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Andorra', 'AD', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Angola', 'AO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Anguilla', 'AI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Antarctica', 'AQ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Antigua and Barbuda', 'AG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Argentina', 'AR', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Armenia', 'AM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Aruba', 'AW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Australia', 'AU', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Austria', 'AT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Azerbaijan', 'AZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bahamas', 'BS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bahrain', 'BH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bangladesh', 'BD', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Barbados', 'BB', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Belarus', 'BY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Belgium', 'BE', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Belize', 'BZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Benin', 'BJ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bermuda', 'BM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bhutan', 'BT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bosnia and Herzegovina', 'BA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Botswana', 'BW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bouvet Island', 'BV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Brazil', 'BR', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('British Indian Ocean Territory', 'IO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Brunei Darussalam', 'BN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Bulgaria', 'BG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Burkina Faso', 'BF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Burundi', 'BI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cambodia', 'KH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cameroon', 'CM', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Canada', 'CA', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cape Verde', 'CV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cayman Islands', 'KY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Central African Republic', 'CF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Chad', 'TD', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Chile', 'CL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('China', 'CN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Christmas Island', 'CX', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cocos (Keeling) Islands', 'CC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Colombia', 'CO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Comoros', 'KM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Congo', 'CG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cook Islands', 'CK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Costa Rica', 'CR', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Croatia', 'HR', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cuba', 'CU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Cyprus', 'CY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Czech Republic', 'CZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Denmark', 'DK', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Djibouti', 'DJ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Dominica', 'DM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Dominican Republic', 'DO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Ecuador', 'EC', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Egypt', 'EG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('El Salvador', 'SV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Equatorial Guinea', 'GQ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Eritrea', 'ER', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Estonia', 'EE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Ethiopia', 'ET', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Falkland Islands (Malvinas)' ,'FK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Faroe Islands', 'FO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Fiji', 'FJ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Finland', 'FI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('France', 'FR', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('French Guiana', 'GF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('French Polynesia', 'PF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('French Southern Territories', 'TF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Gabon', 'GA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Gambia', 'GM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Georgia', 'GE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Germany', 'DE', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Ghana', 'GH', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Gibraltar', 'GI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Greece', 'GR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Greenland', 'GL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Grenada', 'GD', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guadeloupe', 'GP', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guam', 'GU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guatemala', 'GT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guernsey', 'GG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guinea', 'GN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guinea-Bissau', 'GW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Guyana', 'GY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Haiti', 'HT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Heard Island and McDonald Islands', 'HM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Holy See (Vatican City State)' ,'VA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Honduras', 'HN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Hong Kong', 'HK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Hungary', 'HU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Iceland', 'IS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('India', 'IN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Indonesia', 'ID', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Iraq', 'IQ', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Ireland', 'IE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Isle of Man', 'IM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Israel', 'IL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Italy', 'IT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Jamaica', 'JM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Japan', 'JP', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Jersey', 'JE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Jordan', 'JO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Kazakhstan', 'KZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Kenya', 'KE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Kiribati', 'KI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Kuwait', 'KW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Kyrgyzstan', 'KG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Lao Peoples Democratic Republic', 'LA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Latvia', 'LV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Lebanon', 'LB', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Lesotho', 'LS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Liberia', 'LR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Libya', 'LY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Liechtenstein', 'LI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Lithuania', 'LT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Luxembourg', 'LU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Macao', 'MO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Madagascar', 'MG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Malawi', 'MW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Malaysia', 'MY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Maldives', 'MV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mali', 'ML', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Malta', 'MT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Marshall Islands', 'MH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Martinique', 'MQ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mauritania', 'MR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mauritius', 'MU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mayotte', 'YT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mexico', 'MX', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Monaco', 'MC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mongolia', 'MN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Montenegro', 'ME', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Montserrat', 'MS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Morocco', 'MA', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Mozambique', 'MZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Myanmar', 'MM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Namibia', 'NA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Nauru', 'NR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Nepal', 'NP', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Netherlands', 'NL', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('New Caledonia', 'NC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('New Zealand', 'NZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Nicaragua', 'NI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Niger', 'NE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Nigeria', 'NG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Niue', 'NU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Norfolk Island', 'NF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Northern Mariana Islands', 'MP', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Norway', 'NO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Oman', 'OM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Pakistan', 'PK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Palau', 'PW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Panama', 'PA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Papua New Guinea', 'PG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Paraguay', 'PY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Peru', 'PE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Philippines', 'PH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Pitcairn', 'PN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Poland', 'PL', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Portugal', 'PT', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Puerto Rico', 'PR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Qatar', 'QA', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Romania', 'RO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Russian Federation', 'RU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Rwanda', 'RW', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saint Kitts and Nevis', 'KN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saint Lucia', 'LC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saint Martin (French part)' ,'MF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saint Pierre and Miquelon', 'PM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saint Vincent and the Grenadines', 'VC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Samoa', 'WS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('San Marino', 'SM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sao Tome and Principe', 'ST', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Saudi Arabia', 'SA', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Senegal', 'SN', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Serbia', 'RS', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Seychelles', 'SC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sierra Leone', 'SL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Singapore', 'SG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sint Maarten (Dutch part)' ,'SX', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Slovakia', 'SK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Slovenia', 'SI', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Solomon Islands', 'SB', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Somalia', 'SO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('South Africa', 'ZA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('South Georgia and the South Sandwich Islands', 'GS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('South Sudan', 'SS', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Spain', 'ES', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sri Lanka', 'LK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sudan', 'SD', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Suriname', 'SR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Svalbard and Jan Mayen', 'SJ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Swaziland', 'SZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Sweden', 'SE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Switzerland', 'CH', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Syrian Arab Republic', 'SY', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Tajikistan', 'TJ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Thailand', 'TH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Timor-Leste', 'TL', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Togo', 'TG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Tokelau', 'TK', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Tonga', 'TO', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Trinidad and Tobago', 'TT', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Tunisia', 'TN', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Turkey', 'TR', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Turkmenistan', 'TM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Turks and Caicos Islands', 'TC', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Tuvalu', 'TV', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Uganda', 'UG', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Ukraine', 'UA', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('United Arab Emirates', 'AE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('United Kingdom', 'GB', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('United States', 'US', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('United States Minor Outlying Islands', 'UM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Uruguay', 'UY', 1);
INSERT INTO country (name, code, fifaQualified) VALUES ('Uzbekistan', 'UZ', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Vanuatu', 'VU', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Viet Nam', 'VN', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Wallis and Futuna', 'WF', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Western Sahara', 'EH', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Yemen', 'YE', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Zambia', 'ZM', 0);
INSERT INTO country (name, code, fifaQualified) VALUES ('Zimbabwe', 'ZW', 0);