SET IDENTITY_INSERT [dbo].[team] ON
INSERT INTO [dbo].[team] ([id], [name]) VALUES (1, N'Tincidunt Congue Incorporated')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (2, N'Ut Tincidunt Vehicula Corporation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (3, N'Pede Praesent Eu LLC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (4, N'Convallis Corporation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (5, N'Amet Consectetuer PC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (6, N'Elit Elit Fermentum Inc.')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (7, N'Ornare Facilisis Limited')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (8, N'Lectus Nullam Suscipit LLC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (9, N'Nibh Dolor LLP')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (10, N'Eget Corporation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (11, N'Magna Sed LLC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (12, N'Et Malesuada Corporation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (13, N'Aenean Institute')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (14, N'Eu Ligula PC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (15, N'Ullamcorper Magna Sed Corporation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (16, N'Nunc Nulla Vulputate Consulting')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (17, N'Bibendum Sed Foundation')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (18, N'Massa Quisque Porttitor Incorporated')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (19, N'Leo Incorporated')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (20, N'Mollis Lectus LLC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (21, N'Dignissim Consulting')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (22, N'Libero Morbi Industries')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (23, N'Quisque Imperdiet LLP')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (24, N'Aliquam Rutrum Ltd')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (25, N'Arcu Vestibulum Associates')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (26, N'Est Arcu Consulting')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (27, N'Scelerisque Sed Industries')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (28, N'Vehicula Inc.')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (29, N'Ut Sagittis Ltd')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (30, N'Eu Corp.')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (31, N'Ornare Tortor At Limited')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (32, N'Nunc Sollicitudin Commodo LLP')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (33, N'Nunc In At Ltd')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (34, N'Blandit Nam LLC')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (35, N'Sodales Elit Industries')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (36, N'Mi Enim LLP')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (37, N'Diam Sed Limited')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (38, N'Orci Donec Company')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (39, N'Quam Elementum LLP')
INSERT INTO [dbo].[team] ([id], [name]) VALUES (40, N'Felis Purus Ac Institute')
SET IDENTITY_INSERT [dbo].[team] OFF
